# Generated by Django 5.2.6 on 2025-09-21 14:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('last_signed_in', models.DateTimeField(blank=True, null=True, verbose_name='last signed in')),
                ('disabled', models.BooleanField(default=False, verbose_name='disabled')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIGN_IN', 'Sign In'), ('SIGN_IN_OUATH', 'Sign In Oauth'), ('SIGN_OUT', 'Sign Out'), ('SIGN_IN_FAIL', 'Sign In Fail'), ('SIGN_IN_OAUTH_FAIL', 'Sign In Oauth Fail')], max_length=50, verbose_name='type')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_audit_logs', related_query_name='security_audit_log', to='auth.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'user security audit log',
                'verbose_name_plural': 'user security audit logs',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('CREDENTIALS', 'Credentials'), ('OAUTH', 'Oauth')], max_length=50, verbose_name='type')),
                ('provider', models.CharField(blank=True, choices=[('credentials', 'Credentials'), ('google', 'Oauth')], max_length=11, verbose_name='provider')),
                ('provider_account_id', models.CharField(blank=True, max_length=255, verbose_name='provider ID')),
                ('token_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='token type')),
                ('scope', models.TextField(blank=True, null=True, verbose_name='scope')),
                ('id_token', models.TextField(blank=True, null=True, verbose_name='ID Token')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', related_query_name='account', to='auth.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_account_id'), name='provider__provider_account_id')],
            },
        ),
    ]
