export enum AppErrorCode {
  "EMAIL_ALREADY_EXISTS" = "EMAIL_ALREADY_EXISTS",
  "INVALID_BODY" = "INVALID_BODY",
  "INVALID_REQUEST" = "INVALID_REQUEST",
  "UNKNOWN_ERROR" = "UNKNOWN_ERROR",
  "TOO_MANY_REQUESTS" = "TOO_MANY_REQUESTS",
  "NOT_FOUND" = "NOT_FOUND",
  "LIMIT_EXCEEDED" = "LIMIT_EXCEEDED",
  "UNAUTHORIZED" = "UNAUTHORIZED",
  "EXPIRED_CODE" = "EXPIRED_CODE",
}
