# Base Layer
FROM python:3.11-slim

# Set Environment Variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gcc \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*



# Set work directory
WORKDIR /app


# Install Python dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && \
    pip install -r requirements.txt


# Copy project
COPY . .

# Collect static files (for production)
# RUN python manage.py collectstatic --noinput

# EXPORT port
EXPOSE 8000

CMD ["daphne","-b","0.0.0.0","-p","8000","config.asgi:application"]